development: &development
  adapter: postgresql
  database: sendagaya_rb_development
  encoding: utf8
  host: localhost
test:
  <<: *development
  database: sendagaya_rb_test
staging:
  url: <%= ENV["DATABASE_URL"] %>
production:
  url: <%= ENV["DATABASE_URL"] %>
